### ISSUE TITLE
Bug: $function 在低版本的 mongodb 下无法运行

### ISSUE THREAD

**Issue by arily** [koishijs/koishi-plugin-dialogue#1]
### Describe the bug

plugin-teach在不支持$function的mongodb数据库下出现问题：
即使触发条件中不包含regex，也会由于使用$function而导致运行失败

### Steps to reproduce

·使用不支持$function的mongodb数据库（比如mongodb atlas M0-M2)
·安装teach插件

·teach添加触发
teach aaa $(help)

### Expected behavior

在添加触发条件时判断运行环境是否支持$function，如果不支持就不添加；
在运行时判断是否支持$function，若不支持就默认数据库中不含有任何regex触发条件，并且在查询时不使用$function。

### Screenshots

2022-05-02 07:36:17 [W] ndefined;1msession 6分拍 260多
                        MongoServerError: $function not allowed in this atlas tier
                            at Connection.onMessage (/home/a/arilychan/node_modules/mongodb/lib/cmap/connection.js:203:30)
                            at MessageStream.<anonymous> (/home/a/arilychan/node_modules/mongodb/lib/cmap/connection.js:63:60)
                            at MessageStream.emit (events.js:400:28)
                            at MessageStream.emit (domain.js:475:12)
                            at processIncomingData (/home/a/arilychan/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
                            at MessageStream._write (/home/a/arilychan/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
                            at writeOrBuffer (internal/streams/writable.js:358:12)
                            at MessageStream.Writable.write (internal/streams/writable.js:303:10)
                            at TLSSocket.ondata (internal/streams/readable.js:731:22)
                            at TLSSocket.emit (events.js:400:28)
                        Middleware stack:
                          - /home/a/arilychan/plugins/koishi-plugin-osu-stat-screenshot/index.js:154:30
                          - /home/a/arilychan/node_modules/@koishijs/plugin-feedback/lib/index.js:81:14
                          - /home/a/arilychan/plugins/koishi-plugin-blackfarts/index.js:62:26
                          - /home/a/arilychan/node_modules/@koishijs/core/lib/node.js:2542:14
                          - /home/a/arilychan/node_modules/@koishijs/core/lib/node.js:2222:14
                          - /home/a/arilychan/node_modules/@koishijs/core/lib/node.js:2681:12
                          - /home/a/arilychan/node_modules/@koishijs/plugin-bind/lib/index.js:82:14

### Versions

- OS: macOS 12.3.1
- Platform: OneBot
- Node version: 16.14.0
- Koishi version: 4.6.1

**Comment by shigma** [comment]
fixed by https://github.com/shigma/minato/commit/70109f64eaacefdd959680a992586418075ba5ad.
