### ISSUE TITLE
无法调用指令插值

### ISSUE THREAD

**Issue by DaBinQwQ** [koishijs/koishi-plugin-dialogue#21]
无法调用指令插值
是我操作问题吗，插件和koishi版本均为最新

`# test $(echo test)
07:50:44   #首次尝试
---
问答已添加，编号为 27。
07:50:44
---
test
07:50:47   #无反应
---
#27 ~ "$(嗯哼 echo test)"
07:54:51   #尝试带nickname的指令
---
问答 27 已成功修改。
07:54:51
---
test
07:55:22   #无反应`

**Comment by medicago087** [comment]
![image](https://user-images.githubusercontent.com/68104673/231027761-8d2b4d14-7b20-42f4-8ac4-2975e8b5d43d.png)
你是否正确安装了 dialogue 全家桶？

**Comment by DaBinQwQ** [comment]
没有启用上下文插件，启用后出现更大的问题，原本可以回复的内容也回复不了了
`
#3
09:07:52

问答 3 的详细信息：
问题：嗯哼
回答：$s你在叫我吗~
生效环境：全局
09:07:52

嗯哼
09:07:59   #无反应
`

**Comment by DaBinQwQ** [comment]
包括主体在内的6个插件均启用

**Comment by DaBinQwQ** [comment]
日志内有报错如下
2023-04-11 09:16:48 [W] session 嗯哼
                        TypeError: Cannot read properties of undefined (reading '0')
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue-flow\lib\index.js:234:22
                            at Lifecycle.bail (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:116:31)
                            at Context.bail (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:619:31)
                            at triggerDialogue (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue\lib\index.js:525:11)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue\lib\index.js:591:12
                            at next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:69)
                            at SleepManage.onMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:67:20)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:40:48
                            at next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:69)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1854:16

**Comment by medicago087** [comment]
坏，那新加的呢？我自己是只启用了context。很眼熟的报错，等其他人看看

**Comment by DaBinQwQ** [comment]
无法使用

# 你好 你好
09:21:25

问答已添加，编号为 28。
09:21:25

你好
09:21:29

#28
09:21:37

发生未知错误。
09:21:37

日志报错如下
2023-04-11 09:21:29 [W] session 你好
                        TypeError: Cannot read properties of undefined (reading '0')
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue-flow\lib\index.js:234:22
                            at Lifecycle.bail (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:116:31)
                            at Context.bail (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:619:31)
                            at triggerDialogue (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue\lib\index.js:525:11)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue\lib\index.js:591:12
                            at next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:69)
                            at SleepManage.onMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:67:20)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:40:48
                            at next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:888:69)
                            at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1850:16
2023-04-11 09:21:37 [W] sqlite > SELECT `id`, `authority`, `onebot`, `name` FROM `user` adjircec WHERE `id` in (1)
2023-04-11 09:21:37 [W] command #28
                        Error: no such column: onebot
                            at f.handleError (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
                            at f.prepare (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\sql.js\dist\sql-wasm.js:90:46)
                            at SQLiteDriver.#exec (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:338:26)
                            at SQLiteDriver.#all (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:350:48)
                            at SQLiteDriver.get (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\driver-sqlite\lib\index.js:277:54)
                            at Selection.execute (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@minatojs\core\lib\index.cjs:384:34)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-dialogue-author\lib\index.js:89:19
                            at async Lifecycle.serial (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis\lib\index.cjs:107:22)
似乎与数据库有关

**Comment by DaBinQwQ** [comment]
关闭上下文后不调用指令的恢复正常，调用指令的仍然无法使用

**Comment by medicago087** [comment]
神秘（
> at SleepManage.onMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:67:20)
at C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-sleep-manage\lib\index.js:40:48

**Comment by DaBinQwQ** [comment]
一夜之间跟用了开塞露一样
设置了但是似乎从没触发过的定时命令凌晨被触发了，早上起来看到赶忙去试一下，可以成功调用指令了
离谱，看来是koishi的什么问题

**Comment by shigma** [comment]
可能是 flow 插件的问题，我看还有其他 issue 说 flow 不可用什么的。
