### ISSUE TITLE
使用指令插值后,问答添加成功但无法触发成功

### ISSUE THREAD

**Issue by axlmly** [koishijs/koishi-plugin-dialogue#33]
![853b6fe576937bd6caab897efaf1ff6b](https://github.com/koishijs/koishi-plugin-dialogue/assets/41771421/c7dbabf0-4f02-4f28-90d6-cc0993fea0b7)
版本:
dlalogue:4.1.3
dialogue-author :1.2.1
dialogue-context:1.0.4
dialogue-flow1.0.4
dialogue-time:1.0.3
dialogue-rate-limit:1.0.3
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Binaries:
    Node: 20.3.1
    Yarn: 4.1.0
Koishi:
    Core: 4.17.4
    Console: 5.26.5
    Koishi Desktop: 1.0.2

使用:
# 你这样是会被红白笑的 => 你这样是要被红白笑的 -E
详情:
问答43的详细信息：
问题：你这样是会被红白笑的
回答：$(dialogue你这样是要被红白笑的)
生效环境：全局

日志无报错

**Comment by opwop1** [comment]
同样问题

**Comment by shigma** [comment]
用的 onebot 适配器吗？

**Comment by opwop1** [comment]
> 用的 onebot 适配器吗？

是的

**Comment by W1ndys** [comment]
同样问题，用的onebot

**Comment by W1ndys** [comment]
测试发现添加test是可以的，其他的内容不行
例如
`# test successful`
问：test
答：任意内容

**Comment by 919334339** [comment]
同样问题，用的官方机器人，可以添加，可以用“#+序号“查看，但不能触发

**Comment by SnowMoonSS** [comment]
应该是同样的问题，能添加上，数据库里也确实有内容，但是无法触发。下面是环境与日志

版本：
koishi-plugin-dialogue: 4.1.3
koishi-plugin-dialogue-context: 1.0.4

System:
    OS: Linux 6.5 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 12th Gen Intel(R) Core(TM) i3-12100

Binaries:
    Node: 20.12.2
    Yarn: 4.1.1

Koishi:
    Core: 4.17.12
    Console: 5.28.4
    Koishi Desktop: 1.1.3

```
2024-08-22 16:58:23 [W] sqlite > SELECT `id`, `flag`, `probS`, `probA`, `original`, `question`, `answer`, `guilds` FROM `dialogue` bcsyxaay WHERE (`flag` & 2 = 2 AND '问答帮助' regexp `original` OR `flag` & 2 = 0 AND `question` = '问答帮助') AND (`flag` & 16 = 0 AND json_array_contains(`guilds`, '"onebot:1234567890"') OR `flag` & 16 = 16 AND NOT((json_array_contains(`guilds`, '"onebot:1234567890"')))) []
2024-08-22 16:58:23 [W] session 问答帮助
                        Error
                            at f.handleError (/home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at c.step (/home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/sql.js/dist/sql-wasm.js:80:205)
                            at /home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/driver-sqlite/lib/index.cjs:364:19
                            at SQLiteDriver._exec (/home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/driver-sqlite/lib/index.cjs:351:22)
                            at SQLiteDriver._all (/home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/driver-sqlite/lib/index.cjs:361:17)
                            at SQLiteDriver.get (/home/snowmoonss/.koishi/data/instances/default/node_modules/@minatojs/driver-sqlite/lib/index.cjs:414:23)
                            at _Selection.execute (/home/snowmoonss/.koishi/data/instances/default/node_modules/minato/lib/index.cjs:796:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Selection.execute (/home/snowmoonss/.koishi/data/instances/default/node_modules/minato/lib/index.cjs:892:18)
                            at async Proxy.get (/home/snowmoonss/.koishi/data/instances/default/node_modules/koishi-plugin-dialogue/lib/index.js:127:25)
```

**Comment by SoloShine** [comment]
最近遇到了类似的问题，可以管理问答，但无法触发，看日志有报sqlite的错。
解决方案：重载“database-sqlite”插件
